language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer install --no-interaction
script: php -q public/index.php
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
notifications:
    on_success: never
    on_failure: never