language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  #- vendor/bin/propel sql:build --overwrite
  #- vendor/bin/propel model:build
script: php -q public/index.php
matrix:
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
notifications:
    on_success: never
    on_failure: never